Repository camaraproject/IdentityAndConsentManagement, pull requests merged in 2024-05, with the labels that each got.

#121 Camara OIDC profile
  documentation/CAMARA-Security-Interoperability.md
Labels: v0.2-candidate

#144 Update README.md
  README.md
Labels: subproject management

#152 Update and review of maintainers.md file
  CODEOWNERS
  MAINTAINERS.MD
Labels: subproject management

#162 Add 3-legged access token definition
  documentation/CAMARA-API-access-and-user-consent.md
Labels: documentation, v0.2-candidate

#155 `CAMARA-API-access-and-user-consent.md` aligment with last decisions made in profile
  documentation/CAMARA-API-access-and-user-consent.md
Labels: documentation, v0.2-candidate

#158 Fix statement about "missing sub claim" in case there is no id token
  documentation/CAMARA-Security-Interoperability.md
Labels: v0.2-candidate
